@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NzI3OTE5OTB9.geCUdBuaywGk1UIUh-p02H2K_jQX0roqK9RUGdWjOvI

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Adonis",
  "email": "Adonis@example.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "https://mtsusidelines.com/wp-content/uploads/2018/11/Creed-2-1.jpg",
  "gym_id": 1
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Ivan@example.com",
  "password": "password"
}

### Exercises index
GET http://localhost:3000/exercises.json

### Exercises create
POST http://localhost:3000/exercises.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Test exercise",
  "description": "sweaty",
  "image_url": "workout.com",
  "video_url": "workout.com"
}

### Exercises show
GET http://localhost:3000/exercises/1.json

### Exercises update
PATCH http://localhost:3000/exercises/10
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "image": "test"
}

### Exercises destroy
DELETE http://localhost:3000/exercises/5
Authorization: Bearer {{jwt}}